apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nuodssjfg-nodejs-gitops
  description: This is GitOps manifest for nuodssjfg-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=nuodssjfg-nodejs
    backstage.io/kubernetes-id: nuodssjfg-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: nuodssjfg-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nuodssjfg-nodejs
